<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LatteVanilla\LatteVanilla.csproj" />
        <EmbeddedResource Include="Fonts/**/*.*" CopyToOutputDirectory="Always"/>
    </ItemGroup>

</Project>
