<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
        <RootNamespace>Latte.Vanilla</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Latte\Latte\Latte.csproj" />
    </ItemGroup>

</Project>
